apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-kubeflow
  region: us-west-2

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 4
  iam:
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AWSCertificateManagerReadOnly
      - arn:aws:iam::aws:policy/AmazonCognitoReadOnly
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
    withAddonPolicies:
      albIngress: true
